#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pefile
Version  : 2017.5.26
Release  : 4
URL      : https://github.com/erocarrera/pefile/archive/v2017.5.26.tar.gz
Source0  : https://github.com/erocarrera/pefile/archive/v2017.5.26.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: pefile-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
_pefile_ is a multi-platform Python module to parse and work with [Portable Executable (aka PE) files](http://en.wikipedia.org/wiki/Portable_Executable). Most of the information contained in the PE headers is accessible as well as all sections' details and their data.

%package python
Summary: python components for the pefile package.
Group: Default

%description python
python components for the pefile package.


%prep
%setup -q -n pefile-2017.5.26

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1496413774
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1496413774
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
