#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pefile
Version  : 2017.8.1
Release  : 5
URL      : https://github.com/erocarrera/pefile/releases/download/v2017.8.1/pefile-2017.8.1.tar.gz
Source0  : https://github.com/erocarrera/pefile/releases/download/v2017.8.1/pefile-2017.8.1.tar.gz
Summary  : Python PE parsing module
Group    : Development/Tools
License  : MIT
Requires: pefile-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
All the PE file basic structures are available with their default names as
        attributes of the instance returned.
        
        Processed elements such as the import table are made available with lowercase
        names, to differentiate them from the upper case basic structure names.
        
        pefile has been tested against many edge cases such as corrupted and malformed
        PEs as well as malware, which often attempts to abuse the format way beyond its
        standard use. To the best of my knowledge most of the abuse is handled
        gracefully.
        
        Copyright (c) 2005-2017 Ero Carrera <ero.carrera@gmail.com>
        
        All rights reserved.
        
        For detailed copyright information see the file COPYING in the root of the
        distribution archive.

%package python
Summary: python components for the pefile package.
Group: Default

%description python
python components for the pefile package.


%prep
%setup -q -n pefile-2017.8.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1501635565
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1501635565
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
