#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pefile
Version  : 2016.3.28
Release  : 1
URL      : https://github.com/erocarrera/pefile/files/192316/pefile-2016.3.28.tar.gz
Source0  : https://github.com/erocarrera/pefile/files/192316/pefile-2016.3.28.tar.gz
Summary  : Python PE parsing module
Group    : Development/Tools
License  : MIT
Requires: pefile-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : setuptools

%description
_pefile_ is a multi-platform Python module to parse and work with [Portable Executable (aka PE) files](http://en.wikipedia.org/wiki/Portable_Executable). Most of the information contained in the PE headers is accessible as well as all sections' details and their data.

%package python
Summary: python components for the pefile package.
Group: Default

%description python
python components for the pefile package.


%prep
%setup -q -n pefile-2016.3.28

%build
export LANG=C
python2 setup.py build -b py2

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
